### ISSUE TITLE
Extending the map width size to 255 tiles

### ISSUE THREAD

**Issue by Faidon** [lronaldo/cpctelera#108]
Hi,
This is a question for a possible enhancement in the future.
I am creating some maps based on arcade game, and in order to match the arrangement of objects and graphics as they are in the arcade, they have a width of 200 tiles (each tile is 4px X 4px ). 
The next step was to put the map and scroll it in order to see how it looks, but i saw that i cannot scroll a map of such a width, it scrolled, but when reaching a certain X value the code stuck. 

I was able to have a scroll and see till the 172th tile column with a setting of MAXSCROLL=132. Any value > 132 caused a crash when i scrolled to the rightmost area. The fact that worked will 172th was a wonder because as the manual says, the map_width is restricted to 127 tiles in width because of X value in  cpct_etm_drawTileBox2x4 u8 x, u8 y, u8 w, u8 h, u8 map_width, void* pvideomem, const void* ptilemap).

Is it possible to do an enhancement to this function and support the full map width of 255 tiles - which by the way matches the capability if its declaration (u8) ?

Also, how possible is to extend the Ymax as well to e.g. from current max which is 63 to 128 in order to deploy vertical scrolling in a map that extends upwards?

**Comment by lronaldo** [comment]
Hi @Faidon ,

First of all, good luck with your game. Hope you can do a great conversion and enjoy on the proccess of creating it. I also hope that CPCtelera can help you achieve what you want more comfortably than creating everything from scratch by yourself.

With respect to your question, first I want to say that you did not properly read the documentation. The best piece of advice I can give you when using CPCtelera, same I always tell my students, is carefully read all the documentation of the functions you use. Please, do not make assumptions. That would certainly put you into many troubles. The low-level library CPCtelera includes is heavily optimized, but that comes with a prize: the programmer must know and control the details. Many functions will missbehave if you do not carefully respect ranges and input preconditions. This is because the functions do not perform checks in order to be much faster. Please, take this into account and do carefully read the documentation of the functions you use.

In this sense, `cpct_etm_drawTileBox2x4` works with maps up to 255 tiles width. There is no need to change anything to let the function do that, as it already does that. map_width is not restricted to 127, you can safely use any byte-sized value. Your assumption is wrong because you asked in CPCWiki forums instead of carefully reading documentation by yourself. Some fellows did their best to help you, but neither them nor you payed enough attention to details. Please, do not assume that C declarations imply a full range of values. Ranges have other limitations do to the calculations that must be carried out and the resulting performance required. 

In this case, limitations apply to `x` and `y` values, not to `map_width`. As the documentation says, `x` is limited to the range [1-127] and `y` to the range [1-63]. This is due to the fact that `x` has to be multiplied by 2 (as each tile is 2 bytes-wide) and `y` by 4 (same reason, but 4-byte-high). 

These limitations can be removed, of course. In general, there are almost no limitations that cannot be removed when programming. However, removing these limitations always comes with a cost. It is not free from the time-cost point of view of the function. In fact, if you so wish to remove the limitation, the fastest way to do so is buy manually introducing a patch in the code by yourself. You can do this:
1. Open the file `cpctelera/src/easytilemaps/cpct_etm_drawTileBox2x4.asm`
2. Go to the line 251.
3. Substitute lines 251-254 that should contain this:
```
   ;; Third, add up 2 * x
   ld    a, c      ;; [1] A = x coordinate
   add   a         ;; [1] A = 2x (Ignore carry, because x will be in the range [1,127])
   add__hl_a       ;; [5] HL += 2x, so finally HL = 0x50 * int(y/2) + 0x2000
```
by this
```
   ;; Third, add up 2 * x
   ld    e, c     ;; [1] /
   ld    d, #0    ;; [2] \ DE = A (DE = x coordinate in 16-bits)
   add   hl, de   ;; [3] / HL = HL + 2*DE
   add   hl, de   ;; [3] \ (Adds 2x to HL, to point to HL = 0x50 * int(y/2) + 0x2000)
```
4. In the terminal go to cpctelera main folder `cd $CPCT_PATH`
5. Type in `make clean && make` to compile the changes

With that change, you will be able to overcome the limit of 127 in the range of the `x` value at the expense of 2 more microseconds each time you use `cpct_drawTileBox2x4`.

Similarly, a patch for the `y` range might be created, but the cost will be greater.

In any case, I personally think that you should think of a different approach if you aim for bigger tilemaps. Having big tilemaps uncompressed in memory has an enormous memory cost. It is much preferable to create a rolling-map data structure and then add new rows/columns as you scroll. That lets you have greater tilemaps without any limitation apart from the memory itself.

I won't add these patches to current stable release, as the implementation of 2x4 tilemaps is deprecated. I have to develop a new one following same approach that CPCtelera 1.5 uses for 4x8  tiles, which is much faster and has less limitations.

Good luck with your project. We will try to help you whenever that is possible.

**Comment by Faidon** [comment]
Hi Ronaldo,

First of all i appreciate that you took the time to answer and provide a solution for this.
Obviously, i am a newby in cpctelera and there are many aspects that i need to study
before proceeding to sw implementation. But before doing this i have to fulfill two milestones:

1. Finish the graphics. 
2. Study the cpctelera platform, its various examples 
and documentation and create an effort estimation if i decide to program this project.

if 2. gives a reasonable time  to complete this project (which is always effort estimation times two  :)), 
then i will proceed. Otherwise, i will just donate graphics to the community.

Yes, i was hasty regarding the details i have no problem to admit this, because at this stage 
i want to focus with the graphic design, and produce a scrolling of a full map without investing 
much time at this stage in programming, as i want to finish graphics first,  
have a scrolling demo as fast as possible to verify that i am on the right track regarding the 
proportions of objects, graphics etc.

Saying this, i would like to clarify that when i wrote that "map_width is restricted to 127", 
i continue by saying "because of X" meaning that the restriction ox X imposes an indirect restriction 
to the value of map_width as well - as the manual says. 

Besides, I would never say the map width is directly restricted to 127,because with my own eyes in my first example i saw that in my tilemap, i was able to scroll a map of 172 tiles and watch the 172th column drawn on the screen,  as i wrote in the cpcwiki (which bypasses the number of 127). 
Perhaps i did not  express myself in the best way. 

Do not take me wrong, i had read the documentation and had seen the restriction
of x<=127 but after watching in practice that x could take even the value of 172 without 
the problems the manual says that you encounter problems (corruptions) when setting a value of >=127  i ignored this assumed that it could be a left over from older versions (this is where i was hasty in my judgement :) ) ,and decided to ask the forum, which is full of people that have prior experience in practise with this platform and get some opinions. 
Maybe there could be a workaround that already exists and there is no need to reinvent the wheel. 

And the workaround you gave, should solve the problem. and i thank you for your help. 
I will also think about your other proposal you suggested, if and when the time comes!
Good luck with the platform, it is an amazing tool for the community. Hope to see new version soon!

kind regards
Faidon
