### ISSUE TITLE
Issue when using 2cdt 

### ISSUE THREAD

**Issue by reymagnus** [lronaldo/cpctelera#157]
I have tried to convert the game.bin to game.cdt same as this video:
https://www.youtube.com/watch?v=UamFYG8teJk
But with the new package of cpctelera-master, now I need to use 2cdt in replace of cpc2cdt.

When I trying to convert the game.bin the 2cdt returns the help text and doesn't work.

I tried this commands and always is the same result (the output with the help text):

2cdt game.bin game.cdt
2cdt -r GAME game.bin game.cdt
2cdt -r game.bin game.cdt GAME -X &0x4000
2cdt -r PRUEBA1 game.bin game.cdt -X &0x4000
2cdt -r PRUEBA1 game.bin game.cdt -X &0x4000 -L &0x4000
2cdt -r PRUEBA1 game.bin game.cdt -X &4000 -L &4000
2cdt -r PRUEBA1 game.bin game.cdt -X 4000 -L 4000
2cdt -r -X 4000 -L 4000 PRUEBA1 game.bin game.cdt
2cdt -r -X &4000 -L &4000 PRUEBA1 game.bin game.cdt
2cdt -r -X &0x4000 -L &0x4000 PRUEBA1 game.bin game.cdt

What is wrong, I need to install anything else or reinstalling?

What is the right option to convert the .bin file to .cdt with 2cdt?

Another alternatives?

Thanks.
PS: attach to this message, the current directory of cpctelera tools and error.
![Captura de pantalla de 2022-03-23 22-30-47](https://user-images.githubusercontent.com/5332593/159836585-647897e0-ad8f-4ea6-869a-46ec644237b8.png)

![Captura de pantalla de 2022-03-23 22-28-08](https://user-images.githubusercontent.com/5332593/159836317-870ce901-7c91-43d2-8eff-f3550a883a54.png)

**Comment by lronaldo** [comment]
Hi @reymagnus,

I assume that this should be the first time you use CPCtelera, and that can easily be the source of the confusion. `2cdt` is not new to CPCtelera: it has been in CPCtelera since its first version. In fact, it is `cpc2cdt` the one which is new, and that's the reason for it not being in CPCtelera-master, which is the branch you are using. `cpc2cdt` is included in the current development branch of CPCtelera, which is the one we use in the video you are referencing. Therefore, the solution to your problem is to download and install [CPCtelera 1.5/dev](https://github.com/lronaldo/cpctelera/tree/development) (the current development branch) if you want to follow the classroom lessons you are referencing. You may want to see the [video in which I explain the recommended way to currently install CPCtelera 1.5/dev](https://www.youtube.com/watch?v=6Z8pWxTbF0g).

Alternatively, it is also possible to use `2cdt` if you wanted to. However, it seems that you have not checked the output of `2cdt`. `2cdt` does not work as one might expect, and it *always* prints the help message, even when it does what was told to do. So, some of your commands have probably worked as expected, but you might have not checked its output because the message has driven you into thinking it wasn't working.

Hope this helps.

**Comment by reymagnus** [comment]
Thanks for the help, I have already installed cpctelera 1.5 but now I need to configure cpct_rvm, could you bring me some information or link to configure Retro Virtual Machine same as is showed in the video? thanks.
