### ISSUE TITLE
Img2CPC add #define for width and height in byte in .h file

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#29]
Add size (width and height) in byte in the header of generated sprites.

In this way, the size is automaticaly computed for drawing the sprites with cpctelera and if sprite has changed the new size is directly updated.

ex:
```
// Data created with Img2CPC - (c) Retroworks - 2007-2015
#ifndef _SRC_SPRITES_SPR_H_
#define _SRC_SPRITES_SPR_H_

#include <types.h>

#define G_SPR_W 11
#define G_SPR_H 19
extern const u8 g_spr[209];

#endif
```

**Comment by lronaldo** [comment]
@AugustoRuiz I was also thinking about this feature @Arnaud6128 is describing a couple of days ago. I think it is really interesting to have. Moreover, I add a couple of ideas to improve it:

1. Instead of generating the number of bytes in the array (extern const u8 g_spr[209]) it will be nice to have it as a multiplication (extern const u8 g_spr[11*19]). Compiler will generate a constant on assembly, but it will be clearer for humans.
2. It will also be useful to have a configurable output identifier. Right now, identifiers are generated by adding a prefix "g" to the filename of the image with a leading underscore. Would it be possible to have a modifier for giving the exact name of the identifier (apart from appended numbers at the end)?

**Comment by AugustoRuiz** [comment]
Hi! Actually the second feature is already implemented. Use the -bn or
--baseName to specify the prefix to use...

Will have a look at the first one, seems really easy to implement ;)

**Comment by lronaldo** [comment]
@AugustoRuiz I wasn't referring to --baseName functionality. That is already being used and works perfectly :smile:. I was referring to a new functionallity to completely replace the ID of the arrays generated. Something that let you define the complete name, not the prefix. For instance, imagine a file `sprite.png` containing a 16x16 sprite. On converting it using `--baseName global`, the output would be `extern const u8 global_sprite[256] = {...`. The idea would be to have something like `--c-identifier spider`, so that the output would be `extern const u8 spider[256]`.

**Comment by AugustoRuiz** [comment]
Will be implemented as a modifier to baseName switch, called --absoluteBaseName or -abn. If specified, the basename used will be the name of the identifier used, and it will not combine the current file name into the identifier.

Take into account that if you use this with several files in the command line, you will end up with repeated identifiers, so that will not be allowed. If you use -abn switch, you will be restricted to a single input file... or should it use a sequential numbering for that case?

**Comment by lronaldo** [comment]
I think that sequential numbering is more appropriate than restricting to 1 file, from the user point of view.

**Comment by lronaldo** [comment]
Latest version in master Implementes this request. It will be improved, but it is already working in master branch.
