### ISSUE TITLE
Path dependency in build_config.mk

### ISSUE THREAD

**Issue by Octoate** [lronaldo/cpctelera#3]
Hi,
when I create a new project with CPCtelera the build_config.mk contains an absolute path to the CPCtelera development kit (CPCT_PATH variable). If I change my computer or work together in a team this means, that I have to change the path in the build_config.mk file. It would be great if CPCtelera can work without this path and autodetect its installation path. Maybe it is possible to execute a "whereis cpct_mkproject" in the script and use this as the path in this variable!?

CU Tim

**Comment by lronaldo** [comment]
Thank you for your idea, Tim. 

Right now, path is completely static, as you said, meaning that you can't move CPCtelera main folder from its install path. Also, it makes it difficult for you to move project folders across different computers.

I think we should give it a thought, to think of the best way to automate this path's detection. I didn't want to do it on first place because Makefiles are somethimes treacherous with these things and could be a source of problems across platforms. However, I think your use case is very interesting and deserves consideration. So, the only thing that worries me is creating a solution compatible across systems and platforms.

I'm going to open a new branch and make some tests. If you try something, please let me know :).

**Comment by Octoate** [comment]
Well, I guess the best way would be to introduce a environment variable during the setup process of CPCtelera. It should be possible to add an "export" line to the ".profile" file of the users home directory which can be used later in the makefile. That should - at least - work under Linux and Windows (I am using Cygwin at the moment). 

I've tried to get the path with $(shell <command>) in the makefile, but this seems not to be a good solution, because some of the tools (e.g. realpath) seem not to be available on all platforms and it is necessary to parse the output path for the main path of CPCtelera.

**Comment by lronaldo** [comment]
Seems much difficult than it should. I cannot find a way to automate everything other than the environment variable. I usually don't like environment variables, but it seems there is no better solution.

The other alternative is having another script that automatically changes CPCT_PATH makefile variable contents. The drawback is that you should manually execute the script each time you move your project.

**Comment by Octoate** [comment]
Not only when I move the project, but when I use another development system. At the moment, I have a git repository for my developments and a Linux and a Windows machine. I am also sharing the code with another developer, who installed it in another location.
I will hopefully have time to test your changes this evening. Thanks for changing it :+1:

**Comment by lronaldo** [comment]
You're welcome, man :). I've tested it on Arch Linux and Cygwin, and now project folders can be moved to different directories and they still work perfectly. They should also work on different computers having this last revision (still untested). I still hadn't have opportunity to test it on OSX. 

The new cpct_mkproject script configures the project to use environment variable when it founds it. If it does not found the variable CPCT_PATH on the environment, it adds the fixed path to build_config.mk and shows a warning on the terminal.

This is candidate to have more improvements in the future, but I think it will suit most needs in its present status :).
