### ISSUE TITLE
setup.sh error

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#31]
Hi.

Current setup.sh complains about "logs" directory not existing inside cpctelera folder:

#########################
#########################
##> directory '/Users/toni/cpctelera/cpctelera/logs' does not exist, and it is required for CPCTelera framework to work propperly. 

Setup runs ok if this folder is manually created.

Tested on MAC and Raspberry pi, both fail.

Regards.

**Comment by lronaldo** [comment]
Yes, you are right. Some recent update should have removed logs/ folder and it is required to store install logs. 

Thank you for reporting :+1:

**Comment by Gurigraphics** [comment]
## Windows installation journey

1- I clicked on "setup.sh". Installation not completed.
The window closed. Did not generate any logs.

2- I found this issue:
https://github.com/lronaldo/cpctelera/issues/31

3- I created the folder "logs".

4- I clicked on "setup.sh" again.

I found this message in the logs folder:

> make: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera'
> make:
> *** No rule to make target 'cleanall'.
> Stop.
> make: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera'

5- I edited the **bash_library.sh** file to add pause and read the error

```
function Error {
   echo
   echo $ {COLOR_LIGHT_RED}
   echo "#########################"
   echo "## UNRECOVERABLE ERROR ##"
   echo "#########################"
   echo "##> $ {COLOR_LIGHT_YELLOW} $ {1} $ {COLOR_NORMAL}"
   echo
   echo "pause"
   read pause
   exit $ 2
}
```
6- I took a print of the error:


![image](https://imgur.com/zKraTF0.png)


7- I checked the bison version that was installed. 

![image](https://imgur.com/Tv8AodG.png)

Cygwin setup to uninstall this version.

Cygwin setup to install the previous version. 

![image](https://imgur.com/4S5LQl8.png)

The error remained the same.


8- I added the folder C:\cygwin64\bin to the system variables PATH

Fixed bison error.

New error Mono: 

![image](https://imgur.com/uZ2Pd80.png)

9- Cygwin setup to install "mono"

There was only "monotone" in the options.

Download and install mono: https://www.mono-project.com/download/stable/

The error remained. 

10- mono --version no work
Mono cmd menu no install in path 
I added the folder C:\Program Files\Mono\bin to the PATH of system variables.

Fixed mono error.

11- Freeimage error

![image](https://imgur.com/NQlJntY.png)

Cygwin setup there is no "freeimage"

**Download freeimage**:
https://sourceforge.net/projects/freeimage/files/Binary%20Distribution/3.18.0/FreeImage3180Win32Win64.zip/download

**Download expdef**
http://purefractalsolutions.com/show.php?a=utils/expdef

Go to folder FreeImage3180Win32Win64\FreeImage\Dist\x32
Paste here executable

Create a .def file 'libfreeimage.def', which contains all symbols exported by the FreeImage library:
`expdef.exe -p -o path\FreeImage\Dist\x32\FreeImage.dll >path\Dist\x32\libfreeimage.def`

Create the GCC compatible import library 'libfreeimage.a':
`dlltool --add-underscore -d libfreeimage.def -l libfreeimage.a`

Copy libfreeimage.a to folder C:\cygwin64\lib
Copy libfreeimage.h to C:\cygwin64\usr\include
Copy FreeImage.dll to folder C:\cygwin64\bin

FreeImage error fixed.

12- Error tools
![image](https://imgur.com/15vagGQ.png)

13- Clean install
`cmd: setup.sh -cri`

Same error. 

14- Go to path\cpctelera\cpctelera\tools
`cmd: make`

15- Go to path\cpctelera\cpctelera
`cmd: make`

16- New install
`cmd: setup.sh`

17- Test make error
![image](https://imgur.com/UAoCG5S.png)

18- Add to PATH

> C:\msys\1.0\home\cpctelera\cpctelera\tools\sdcc-3.6.8-r9946\bin
> C:\msys\1.0\home\cpctelera\cpctelera\tools\scripts
> C:\msys\1.0\home\cpctelera\cpctelera\tools\img2cpc\bin
> C:\msys\1.0\home\cpctelera\cpctelera\tools
> C:\msys\1.0\home\cpctelera\cpctelera\tools\arkosTracker-1.0\tools

19- New setup error
![image](https://imgur.com/n3Hgs3R.png)

20- tool_building.log

> make: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools'
> [1;31;49m[ToolMaker][1;33;49m Building  2cdt...[0;39;49m
> make[1]: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/2cdt'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/2cdt'
> [1;31;49m[ToolMaker][1;33;49m Building  hex2bin-2.0...[0;39;49m
> make[1]: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/hex2bin-2.0'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/hex2bin-2.0'
> [1;31;49m[ToolMaker][1;33;49m Building  iDSK-0.13...[0;39;49m
> make[1]: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/iDSK-0.13'
> make[1]: 'bin/iDSK' is up to date.
> make[1]: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/iDSK-0.13'
> [1;31;49m[ToolMaker][1;33;49m Building  sdcc-3.6.8-r9946...[0;39;49m
> make[1]: Entering directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/sdcc-3.6.8-r9946'
> Configuring SDCC for z80...
> cd src && ./configure_sdcc_for_z80.sh
> /cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/sdcc-3.6.8-r9946/src
> configure: error: invalid variable name: `0'
> !!ERROR!!: SDCC was not adequately configured for some reason.
> make[1]: *** [Makefile:59: sdcc] Error 1
> make[1]: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools/sdcc-3.6.8-r9946'
> make: *** [Makefile:74: sdcc-3.6.8-r9946] Error 2
> make: Leaving directory '/cygdrive/c/msys/1.0/home/cpctelera/cpctelera/tools'
> 

## GAME OVER
Here I gave up.
Installation time: 10h
- Maybe the error is repeated folder: home\cpctelera\cpctelera
- Or this Home: C:\msys\1.0\home\cpctelera\cpctelera
- And FreeImage maybe I did it wrong or put it in the wrong place.

## Suggestions

**Suggestion 1**:
Update reference Windows installation

> 
> Under Windows Mono and FreeImage also is required
> how install  "freeimage" if in Cygwin setup there is no "freeimage", "libfreeimage" etc.

**Suggestion 3**: Insert "logs" folder in cpctelera folder to generate logs

**Suggestion 4**: Insert "pause" in bash_library.sh to read errors

```
   echo "pause"
   read pause
   exit $ 2
}
```

**Comment by lronaldo** [comment]
@Gurigraphics I'm quite sorry to tell you this, because you have done many things, but all you have done starts from a base common error you made at step one

 > 1- I clicked on "setup.sh". Installation not completed.

Clicking on setup.sh is definitely not the right way to install CPCtelera. You have being trying to install CPCtelera on Windows directly, probably under git-bash shell or mingw. You have not run setup.sh under Cygwin, and that explains why you get errors from software already being installed under Cygwin but not being found by CPCtelera. You have being blaming the wrong culprit. CPCtelera software tests are as simple as checking for commands or files being available. If that fails, it means effectively that the software is not installed. And if you already installed it under Cygwin and is present, clearly you are executing setup.sh outside Cygwin.

Therefore, the solution to all these problems is as simple as opening Cygwin terminal and running ./setup.sh there. The rest is just following CPCtelera install instructions. Past week I assisted some students installing it under Cygwin with no more problems than having to install required dependencies (using Cygwin setup.exe). 

You may found other problems. No software is free from having problems. But these are not related to CPCtelera official support. CPCtelera is not tested nor supported under MSYS or git-bash. There is no need to add a pause in bash_library.sh if you follow instructions and run setup.sh from terminal and not double-clicking. There is no need for mono under Windows, as Windows already has .NET framework, and that is only required to run Arkos Tracker. Moreover, CPCtelera logs/ folder problem was solved on 2016, in this commit https://github.com/lronaldo/cpctelera/commit/222b4294208e92e3f24868a473633bc9d9c84843.

As I said, I'm quite sorry to having to tell you this, as I know you have made a great effort. Just hope it works as expected when you run it inside Cygwin.

**Comment by Gurigraphics** [comment]
Yes! I also tried opening with drag file in Cygwin, but it always opened with normal cmd.  
Then I thought it was normal.
This simple command really execute in Cygwin
./setup.sh 

Anyway, I didn't even open a new issue because I knew I was doing something wrong. 
Only I to complain about it. But without the logs I couldn't know what it was.
And the windows tutorial on youtube was from an old system.

But it was fun. Lots of things I don't know. 
It seems magical that all of this works together. ^^

Another day I try again. Thanks for tip
