### ISSUE TITLE
Img2CPC set tileset variable name according to file name

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#37]
When generated several sprites with **tileset** argument.
_ex:
$(eval $(call IMG2SPRITES,src/sprites/monster.png,0,g,2,0,$(PALETTE),tileset,src/gen_src))
$(eval $(call IMG2SPRITES,src/sprites/monster1.png,0,g,2,0,$(PALETTE),tileset,src/gen_src))_

All generated files have the same tileset variable **g_tileset**

It could be a good idea to prefix tileset variable by the file name.
_ex:
g_monster_tileset[10];
g_monster1_tileset[10];_

Thanks.

**Comment by lronaldo** [comment]
Yes, you are right in that tileset variables should have different names to prevent this from happening. However, I have a question, why do you want to generate different tilesets out of monsters? What is your purpose in this case?

As a workaround, you may change prefix to have two different names based on their prefixes. So, If you chage your code into this:
```
$(eval $(call IMG2SPRITES,src/sprites/monster.png,0,g_monster,2,0,$(PALETTE),tileset,src/gen_src))
$(eval $(call IMG2SPRITES,src/sprites/monster1.png,0,g_monster1,2,0,$(PALETTE),tileset,src/gen_src))
```
you'll get what you expected to get `g_monster_tileset` and `g_monster1_tileset`.

**Comment by Arnaud6128** [comment]
I'm trying to avoid to use my C function to clip sprite (draw line per line and very slow). 
With sprites tiled on width i can draw only the visible parts of them. Of course the drawback is i must call several time the cpct_drawSprite.

It's an experimentation :smile:

Thanks for prefix workaround.

**Comment by lronaldo** [comment]
Ok, I understand your idea, but you don't need the tileset for that. The tileset is an array of pointers to all the generated sprites. That's only useful if you are going to use the sprites as a set of tiles for easytilemap functions. You can do the same without generating tilsets. You'll have your sprites and you can arrange them as you wish.

**Comment by Arnaud6128** [comment]
I have worked on my tiled sprite drawing and in order to draw sprite i need to know the width of the full sprite.

Is there another way to have this information except from the tileset array generated ? 
_spriteWidth = sizeof(gTileset)/sizeof(u8*)_

If this information is not available what do you think about adding this information in generated files ?

Another suggestion is to add an option to generate masked tileset.

Thanks.

**Comment by lronaldo** [comment]
@Arnaud6128 The expression `spriteWidth = sizeof(gTileset)/sizeof(u8*)` will not give you the width of the sprite unless your sprite has only 1 dimension in tiles (i.e. it is composed by tiles disposed only in a horizontal axis, not in vertical). Or are you referring to the linear size of the tileset?

This information is not generated because tilesets have been designed as a component of tilemaps, not define tiled sprites. I personally didn't ever think of using tiles as kind of "subsprites". That's the same reason for not having masked tiles. However, I recommend you to use `cpct_drawSpriteMaskedAlignedTable` for masked sprites and get rid of interlaced masks, as they take too much space in memory.

I take note of your suggestions. Don't think they will be implemented soon, because of the priorities of the next release, but thank you, as always :smile:

**Comment by Arnaud6128** [comment]
Yes my sprites are 1 dimension in order to simulate horizontal scrolling.
I'll to take a lot to cpct_drawSpriteMaskedAlignedTable.

It's really not a priority and i have solutions. There are already very interesting features to come with 1.5 :wink:

**Comment by lronaldo** [comment]
New macro IMG2SP included in current development branch lets you name your tileset variable with the name you prefer. I think this solves the issue :).
