### ISSUE TITLE
cpctm_createTransparentMaskTable does not work properly with colors indexes != 0

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#40]
Hello.

I am not able to create transparency tables using cpctm_createTransparentMaskTable macro using a color index != 0. I think it works with differents indexes, but for example not with 15, the color is not considered transparent.

cpctm_createTransparentMaskTable(g_transparencyMaskTable, 0x0800, M0, 15);

As a workaround I change the order of my palette.

Regards.

**Comment by lronaldo** [comment]
Yes, this is a mistake in the documentation. Tables are completely correct. cpctm_createTransparentMaskTable works fine. The problem is the algoritm used in cpct_drawSpriteMaskedAlignedTable. That algorithm is only valid if transparent pixels are 0's. Therefore, if you use any other palette colour as transparent it will produce odd effects. 

Using these tables to make other indexes transparent is possible, but it will cost 1 or 2 extra cycles per pixel. This is the reason why it is still not implemented. 

However, documentation of cpct_drawSpriteMaskedAlignedTable should advice against using it with indexes different than 0.

**Comment by AmstradGamer** [comment]
Ok!

Thank you!
