### ISSUE TITLE
Document cpct_drawSpriteMaskedAlignedTable can only use palette index 0 for transparency

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#46]
When i use an index different of 0, i have not transparency on my sprite masked aligned.

To confirm the problem, i tried with the example of cpctelera and when i changed
`cpctm_createTransparentMaskTable(g_masktable, 0x0100, M0, 0);`
with
`cpctm_createTransparentMaskTable(g_masktable, 0x0100, M0, 1);`
the Alien sprite become opaque.

Is the transparency color must be always black or it's a bug ?
Thanks.

**Comment by AugustoRuiz** [comment]
The transparent color could be any color. Could you please try using
img2cpc to generate the look up tables and compare them to the ones
generated by the macro?

**Comment by Arnaud6128** [comment]
Is the correct command line ? 
`img2cpc.exe -p config_m0.json -f -t 1 -of bin -m 0 alien.png`
(colors firmware = 0 18 5 6 9 11 12 )

Files are totally different :
[tableMaskMem.txt](https://github.com/lronaldo/cpctelera/files/675264/tableMaskMem.txt)
[flipLut.txt](https://github.com/lronaldo/cpctelera/files/675266/flipLut.txt)

**Comment by AugustoRuiz** [comment]
Hello!

flipLut is the look up table to flip the colours, it's not the mask. And
also, be careful, the transparency switch uses the palette index, and index
starts at 0. If your transparent color is firmware color 0, that would be
index 0 in your palette.

In order to generate the tables, you have to specify the -nm (--noMasks)
switch. So you can invoke it like so:

img2cpc -fwp 0,18,5,6,9,11,12 -t 0 -m 0 -nm -of bin alien.png

Also, it's not a good idea to mix json config and switches. Once you
specify a json config, no command line switches are applied.

HTH,



Augusto.

**Comment by Arnaud6128** [comment]
Here the files with transparent index 0 and 1 (it's a zip renamed in txt) :
[tableMask.txt](https://github.com/lronaldo/cpctelera/files/675288/tableMask.txt)

For transparent index 0, AndMasks.bin is equal to memory.
For transparent index 1, they are different.
-> It seems logical according to my problem.

I have no orMasks in memory, it's not needed ?

Arnaud

**Comment by lronaldo** [comment]
Hi @Arnaud6128 and @AugustoRuiz,

   Transparency tables generated by the macro are perfect and there is no bug in the code. The "bug" is in the documentation. [cpct_drawSpriteMaskedAlignedTable](http://lronaldo.github.io/cpctelera/files/sprites/cpct_drawSpriteMaskedAlignedTable-asm.html) does not use OR-Masks and hence it cannot create transparencies using indexes other than 0. The reason is simple: using any other index requires the OR-Masks, which makes the function slower and adds the need to use 256 additional bytes of memory for the table.

   The macro is independent from the function, and that's why it has all the tables. Functions using all the tables for different needs are planned, but still not developed. However, unless there is a good reason, it is strongly recommended to use index 0 for transparency, as it is faster.

   Sorry for taking so long to answer and for the confusion. It will be amended in the documentation.

**Comment by Arnaud6128** [comment]
cpctm_createTransparentMaskTable (TABLENAME, ADDRESS, MODE, **PEN**)

The **PEN** argument is not needed anymore ?

**Comment by lronaldo** [comment]
@Arnaud6128 As I said previously, the macro can create all the tables and is independent from the function. You can generate the tables and use them in other ways or with your own function. No need to cut functionalities there.

**Comment by lronaldo** [comment]
Already documented in current development branch.
