### ISSUE TITLE
iDSk 0.13 : bug with remove option -r, and *.BAS/*BAK files

### ISSUE THREAD

**Issue by gryken2014** [lronaldo/cpctelera#48]
Both file PROG.BAS and PROG.BAK have been removed from the DSK, instead of only PROG.BAK
- There are two DSK files :
[dsk_example.zip](https://github.com/lronaldo/cpctelera/files/1015166/dsk_example.zip)

Platform : linux 64bit MAGEIA

- I create an empty DSK.
- I open it, from an emulator.
- I type some basic lines
- i save "PROG.BAS" from the emulator
- I type some other basic lines
- i save "PROG.BAS" from the emulator

- So, now there are 2 files PROG.BAS and PROG.BAK

- i quit from emulator.

- In  the command line

`[seb@localhost idsk_bug]$ iDSK resu_disc.dsk -l`

> DSK : resu_disc.dsk
> Mode : List Dsk 
> 
> PROG    .BAK : 1 Ko
> PROG    .BAS : 1 Ko

`[seb@localhost idsk_bug]$ iDSK resu_disc.dsk -r PROG.BAK`

> DSK : resu_disc.dsk
> Mode : Effacement fichier dans la DSK
> Fichier Amsdos : PROG.BAK

`[seb@localhost idsk_bug]$ iDSK resu_disc.dsk -l`

> DSK : resu_disc.dsk
> Mode : List Dsk 

Both files has been erased, instead of just PROG.BAS.

**Comment by lronaldo** [comment]
Thank you @gryken2014 for reporting this issue. It is a bug in iDSK that seems to come from libdsk code. Don't now why the code did that, but it was designed to remove all consecutive files with same name without looking at their extension. It might be due to a wrong consideration or some kind of copy-paste, or may be I'm overlooking something. Anyways, it should be solved now.

Update your `CPCtelera` version to latest one (I recommend using last update v1.5 branch), enter `cpctelera/tools/iDSK-0.13` and run `make`. That will install the patch and solve the issue for you.

**Comment by gryken2014** [comment]
- Ok, it's now working OK, with v1.5

- At compilation, there is a warning message.

> src/GestDsk.cpp: In member function ‘void DSK::RemoveFile(int)’:
src/GestDsk.cpp:1073:8: attention : unused variable ‘p’ [-Wunused-variable]
  char *p ;
        ^

It seems that line 1013, is not needed anymore.
The line could also been commented.

Thanks for this patch.

**Comment by lronaldo** [comment]
You are right, man. Thank you again for paying attention to detail and reporting 😄
