### ISSUE TITLE
 cpct_removeInterruptHandler missing in firmware.h

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#51]
Simply add :
`extern u16 cpct_removeInterruptHandler(void) __z88dk_fastcall;`
to 
`cpctelera\src\firmware\firmware.h`

That all 😉

**Comment by lronaldo** [comment]
Thank you @Arnaud6128. As `cpct_removeInterruptHandler` and `cpct_disableFirmware` are indeed the same function, the first one was not in the header and nobody noticed. Now it is fixed in the development branch.

Just one tip. Functions not requiring parameters are not bound to any parameter passing convention, so `__z88dk_fastcall` has no effect in this declaration.
