### ISSUE TITLE
Writing framework location in git-committed framework file feels wrong.

### ISSUE THREAD

**Issue by cpcitor** [lronaldo/cpctelera#55]
# Initial observation

Line [setup.sh:328](https://github.com/lronaldo/cpctelera/blob/fe25f47b2f214f54428da0625a57ef1e873ace73/setup.sh#L328)

    replaceTaggedLine "${CPCT_TAG_MAINPATH}" "CPCT_PATH := ${CPCT_MAIN_DIR}\#${CPCT_TAG_MAINPATH}" "${CPCT_TEMPLATES_CFG}" '#'

modifies file build_config.mk which is managed by git.

This tends to leak local configuration data into repository history, which happened already 7 times, with as many manual fixes:

```
git log -p cpctelera/tools/scripts/templates/build_config.mk | grep "^.CPCT_PATH.*CPCTELERA_PATH" | egrep -vi "CPCT_PATH.*[A-Z]+.*CPCTELERA_PATH" | grep -o ^. | sort | uniq -c

      7 -
      8 +
```

# Possible fixes

One could think about:

* discipline like proofreading all patches before committing. Good in itself, small independent readable commits are best, but does not fix "wrong" feeling.
* writing a script that cleans up repository before commit. Effective yet cost of one more script and does not fix "wrong" feeling.
* changing `setup.sh` so that it creates a purely generated file not checked into git (and even mentioned in .gitignore).

# Why is it even needed to modify a file in the framework own's installation directory? 

* If absolute path is needed it can be computed on the fly in a constant script (possibly cached).
* Example code projects included in framework can refer to framework with relative path or computed absolute path. Like so: `CPCT_PATH      := $(THIS_FILE_PATH)../../../../cpctelera/`
* [cpc-dev-tool-chain](https://github.com/cpcitor/cpc-dev-tool-chain) does not need that. Only projects files, which could be located anywhere in filesystem hierarchy, need to know where framework is, if only to tell which version of framework to use. This feels right.

Please enlighten me.

**Comment by lronaldo** [comment]
Well, this is part of the first version. It is early code and should have been fixed long time ago. It is the kind of thing that enters low priority and never gets fixed. But, of course, you are quite right. 

This was done this way because files included in the framework need to point to the framework to do their first compilation. When CPCtelera is first compiling, it has not had time to set the environment variable `CPCT_PATH`, so cannot be used at that step. Also, CPCtelera's project makefiles include global makefiles that are in `cfg/` folder of the framework. That's why it needs the path. Without it, makefiles won't even work. 

So yes, I think it is time to review this issue and try to find a much better solution. Probably generating a file with the path and including it or something similar.

**Comment by AugustoRuiz** [comment]
Maybe setting the CPCT_PATH variable at setup time, before cpctelera is
compiled, would fix part of the problem.

What I would do is to have global files in the repo as template files, with
markers that should be replaced by the setup script with the appropriate
paths. The setup copies those global config files to a different location
(outside the repo), and replaces those markers by the actual values (they
are well known at setup time). That location is the one that should be
referenced by the config files in projects.

On Thu, Aug 31, 2017 at 9:37 AM, Francisco Gallego <notifications@github.com

**Comment by fidergo-stephane-gourichon** [comment]
Great! Github does not offer "thumbs up" on commits referencing an issue, or a "close" without a comment. Anyway, this cleanly fixes the problem. Congrats!

## Details

This command run right after setup shows that only one file contains the path to CPCTelera installation, and it's indeed the file ignored by git.

```
grep -ri "CPCT_PATH.*=.*$PWD" .
```

```
.../cpctelera/tools/scripts/templates/build_config.mk:CPCT_PATH := ...
```
