### ISSUE TITLE
Error while executing setup.sh on OS X 10.10.5

### ISSUE THREAD

**Issue by dfreniche** [lronaldo/cpctelera#6]
Today I was testing CPCTelera setup against last commit ([7294d05bd24a7803f856632fffdd74aa8c5c6056](https://github.com/lronaldo/cpctelera/commit/7294d05bd24a7803f856632fffdd74aa8c5c6056)) when I found this error

```
>>> Clang has C++11 support...

#########################
## UNRECOVERABLE ERROR ##
#########################
##> You have CLang installed as main compiler and your CLang installation has no support for required C++11 features. Please, upgrade your CLang installation or install GCC >= 4.6 as main compiler.  Under OSX, you may install GCC using brew (http://brew.sh).
```

System:
- OS X 10.10.5
- Xcode 6 installed, using Xcode command line tools from Xcode 6:
```
$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer/
```

This error looks like the clang version used in Xcode 6 does not support some functionality from C++11. But after some digging I found that in [`bash_library.sh`](https://github.com/lronaldo/cpctelera/blob/master/cpctelera/tools/scripts/lib/bash_library.sh) file, you check C++11 compatibility inside function `ensureClangHasRequiredFeatures`.

Instead of using gcc (which would require gcc install from home-brew, another dependency) I've used Apple's LLVM changing:

    gcc "$SRCTMP" -o "$OUTTMP" 2> "$ERRTMP"

for:

    clang++ -std=c++11 -stdlib=libc++ "$SRCTMP" -o "$OUTTMP" 2> "$ERRTMP"

As you can read [here](http://stackoverflow.com/a/14133160/225503)

What's curious is that if you invoke from command line what that function really does (compile a file containing C++ code) you get no errors. So if you compile this file:

```
int main(void) {
	   unsigned char val = 0b00000011;
	   // Checking if __has_feature clang macro is present
	   #ifdef __has_feature
	   
	      // Checking if C++11 Generalized Identifiers is available
	      #if __has_feature(cxx_generalized_initializers)
	         val &= 0b11111110;   // It is available, set identifier bit to 0        
	      #endif
	   
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wextra-tokens"
    // Checkinf if C++11 Ranged fors is available
#ifndef __has_feature(cxx_range_for)
    val &= 0b11111101;   // It is available, set identifier bit to 0
#endif
    
#pragma GCC diagnostic pop
    
	         
	   #endif
	   return val;
	}

```

You get no errors.

Note: I've added the part 

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wextra-tokens"
    // Checkinf if C++11 Ranged fors is available
#ifndef __has_feature(cxx_range_for)
    val &= 0b11111101;   // It is available, set identifier bit to 0
#endif
```

to avoid an ugly warning about parameters not allowed in `ifndef`

When you compile the file you get no errors and a nice .out executable. But setup script now fails in the switch. So to make it work I've commented out:

```
#         *) ERROR_MSG="${MSG_CLANGINSTALLED} This installation does not support C++11 \
#Generalized initializers. ${MSG_UPGRADE}"
#         ;;
```

The problem lies in that check. What are you checking here? Without this default case everything compiles and works

**Comment by lronaldo** [comment]
Yes, you are right. This part of the code is still under revision. We included checks to ensure that compilers have the required C++11 features previous to compiling code. Otherwise, errors will arise during compilation step. It's much easier to inform the user than to start compiling and getting compilation errors.

Anyway, you are mostly right on your revision. However, I think we need some discussion previous to have an adequate implementation. Using this line:
```
clang++ -std=c++11 -stdlib=libc++ "$SRCTMP" -o "$OUTTMP" 2> "$ERRTMP"
```
Should be equivalent to this one
```
g++ -std=c++11 -stdlib=libc++ "$SRCTMP" -o "$OUTTMP" 2> "$ERRTMP"
```
As OSX uses clang++ when calling g++ unless user has set different preferences. I think it would be preferable to maintain second one, as later compilation will use that line of code. To be most concrete the compilation line that will be used later one will be this one:
```
g++ -std=c++0x -O3 -Wall -fsigned-char -o obj/Palette.o -c -Iinclude src/Palette.cc
```
So I think we should use the same set of options.

Regarding #ifndef, I think the error is using #ifndef itself, instead of #if. 

The part you have commented of the script checks the return value of the executable generated. If this executable is badly implemented and does not return appropriate values, it's normal to enter the default case.

Please, let me know what are your thoughts on this. I'm going to implement a fix with this ideas and it would be nice if you could check it :).

Thank you very much for your help! :+1:

**Comment by dfreniche** [comment]
Just tested in terminal proposed g++ change (which is a LLVN frontend) and works. 

Need to clean CPCtelera install dir & setup from scratch. Will update this post

**Comment by lronaldo** [comment]
Can you check that last commit solves this issue? 

Thank you :)
