### ISSUE TITLE
[info] How can I use CPCTelera with an existing project with multiple .c files?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [lronaldo/cpctelera#71]
Hi!

Thanks a lot for you project.
I have coded a game in plain ANSI C, which is in multiple .c files.
I can compile it with ZSDCC from Z88DK.
I would like to compile it with CPCTelera but I have no idea how this can be done.

  Thanks a lot!
  Fabrizio

**Comment by Tonire** [comment]
Why don't you try creating a new CPCTelera project and copying your currently existing .c files inside the "src" folder?
All .c and .s files below src/ will be automatically detected and compiled when you type in “make” at your project folder.

If you check the reference manual [here](https://lronaldo.github.io/cpctelera/files/readme-txt.html#Installing_CPCtelera) and scroll a bit down, you'll see proper instructions on how to create a new CPCTelera project, but basically, just run **cpct_mkproject [project_folder]**

Hope this helps :)

**Comment by Fabrizio-Caruso** [comment]
@Tonire, thanks.
I would also like to pass some parameters to the code.
Ideally I would like to use a standand Makefile because that is what I use for 100 targets (including CPC)

**Comment by fidergo-stephane-gourichon** [comment]
Hello @Fabrizio-Caruso .

You wrote that your project already compiles with zsdcc, that you already have a standard Makefile. What's the motivation / expected benefit of compiling it using CPCTelera?

**Comment by Fabrizio-Caruso** [comment]
@fidergo-stephane-gourichon , CPTelera comes with more powerful APIs than what I am using.

**Comment by Tonire** [comment]
You can still modify the Makefile CPCTelera creates for you. Why don't you modify it so it meets your requirements?

**Comment by Fabrizio-Caruso** [comment]
@Tonire because it is a huge Makefile that calls multile files with lots of definitions and it is not obvious what each part does.
I would like to use CPTelera as a lib for adcc but I have found no documentarion on how to do it.
I would like to use standand dev tools like a plain Makefile that calls sdcc and whatever CPTelera libs are required.

**Comment by Fabrizio-Caruso** [comment]
@Tonire moreover I am compiling my progect for multle (all 8 bit) targets and I would like a to use one makefile for all. I just need to know how to pass multiple files to sdcc (if possible) and how to link and yse CPCTelera libs.

**Comment by lronaldo** [comment]
Hi @Fabrizio-Caruso 

I think we already discussed this matter last time you asked about how to use CPCtelera for your multiplatform project. 

CPCtelera is not a only a lib, but a framework. It uses standard makefiles on top of Linux + sdcc. It is intended to be used by CPC developers. Its included low-level library is CPC-specific, although some functions may be used in other Zip machines.

If you want portability across dozens of Z80 machines, CPCtelera may not be an option for you,  unless you wanted to develop an specific version for the CPC.

If you want to use the low level library in your own project, it shouldn't be straight forward if you use sdcc. CPCtelera installer automatically compiles the library and generates cpctelera.lib under cpctelera/ folder. You can grab that binary and link it to you project. Under cpctelera/src/ you have all source code for the lib as well as the headers. 

As for the documentation, I think it's logical that you haven't found anything. Your needs are outside general CPCtelera scope and very specific. After all, you cannot expect us to document every possible need each developer might have. In any case, we are here to help pointing you in the right direction.

**Comment by Fabrizio-Caruso** [comment]
@lronaldo, Thanks for replying! Thanks for your project!

I don't expect full documentation. I just asked for some hints on how I could use CPCTelera libs with sdcc without the whole framework. I think the framework is cool but it makes sense for CPC-only project that are begun under CPCTelera or any project in just one single file. 
Using the libs independently should be possible. I thought there some some minimal documentaion on how to use the lib.
Thanks and sorry for bothering you guys!

**Comment by lronaldo** [comment]
Sorry for some problems in my latest post with "self-corrected" words. I meant to say that you should have no problem on using the low-level library outside CPCtelera. Full source code and headers of the lib are included under cpctelera/src/ along with its building makefile. You may build it by yourself with sdcc, or you may install CPCtelera, and just grab the cpctelera.lib that gets automatically built. Link the .lib to your project, include cpctelera.h and you should be ready to go. There is no difference with any other C library, but being in Z80 asm. 

As I was saying before, there is no documentation on this because CPCtelera is thought to be used as a framework, and because any programmers wanting to do something special are expected to be self-sufficient with sources and makefiles. After all, someone wanting to do advanced things is expected to know how to do them.

But that doesn't mean we don't want to help you. However, it remains unclear to me what exactly can we do for you. If you want the library, you can grab it and use it. Is it that you are asking how to link with the lib using SDCC? How to use the compiler to do that? Another thing I don't understand is why do you say that CPCtelera is only for single-file projects. Have you had a look at examples? Makefiles in CPCtelera projects automatically compile, assemble and link all C and ASM files under src/ folder of CPCtelera project. There are dozens of examples with many files.

I personally thing that if you want to use the lib in your project, it would be a great idea to start using and understanding the CPCtelera framework first. Once you get a better understanding you may pick up what you need and use it in your project. But with a partial understanding you may just be asking the wrong questions for your actual needs.
