### ISSUE TITLE
Optional clean up CPCTelera installation

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#87]
Hello,

the installation of CPCTelera takes  ~450Mb and without the tools sources, lib and compilation files the size of CPCTelera drops to ~100Mb.

I'll find interesting to have an option to delete these files after the installation of CPCTelera.

**Comment by lronaldo** [comment]
Hi @Arnaud6128 ,

I understand that these extra megabytes of space can be a problem for computers being short. However, I take that this is not the general case nowadays, and it will be less of a problem as time goes by and people buy new hard drives and/or computers.

The thing is, removing source files leaves you with no option but to download and install CPCtelera again if you want to update things and/or make modifications and recompile whatever you needed. The whole point of CPCtelera is to give the use this power, so I see no reason to act on the contrary. Besides, users can easily remove these things by themselves in case they need it. For instance, the 2 folders that take most of the space are `src/` and `obj/` inside `sdcc/` directory. Just by removing these two folders you recover 350MiB, which is what you wrote here.

Therefore, as any user can easily remove these two folders, I see no reason to invest time in creating options or tools to automatize this. Automatizing it can lead users don't really wanting to remove this to do it. I prefer users to do it knowingly and on purpose.

Is there any other reason you may think of it for being an interesting feature?

**Comment by Arnaud6128** [comment]
No, i just had seen the number of file in the cpctelera directory by coping them to my usb key. It takes time and i was wondering if they were really useful. That all :wink:

**Comment by lronaldo** [comment]
Ok then :). In that case, I recommend you to copy CPCtelera as a zip file to USB drives. It's not a problem with the size, but with the huge number of small files. Copying many small files to flash drives is slow and problematic for the drives. Better zip them together before copying to USB.

**Comment by cpcitor** [comment]
Just to add two cents to the conversation.

## General solution to reclaiming space

The traditional way of handling this is to have a `make install` step that generates a self-contained directory tree that includes executable files and all needed data files, doc, etc. This is what the traditional `./configure --prefix=/some/destination/path` does, and same for `cmake -DCMAKE_INSTALL_PREFIX=/some/destination/path`.
After installing, you can remove the source tree without any knowledge like "I can safely remove `src` but not `assets` (or whatever)".

There is a variant called "out-of-source build" where the source tree is not modified at all. All build-time files are created in a dedicated directory. This allows to cleanly build the same source tree for various configurations or even architectures without ever a risk of interference.
Projects using autoconf or cmake are compatible unless the author makes breaking assumptions.

```
mkdir buildtree-for-variant-x
cd buildtree-for-variant-x
cmake -DCMAKE_INSTALL_PREFIX=/some/destination/path ../sourcetree
# or
../sourcetree/configure --prefix=/some/destination/path
make install
```

It is guaranteed that `buildtree-for-variant-x` only contains generated files. After `make install`, it is virtually guaranteed that you can remove it.

## How cpc-dev-tool-chain does it

[cpc-dev-tool-chain](https://github.com/cpcitor/cpc-dev-tool-chain) does not globally implement out-of-source build, but does locally for each of the tools it fetches and compiles.

Here's the size of the biggest part, sdcc, in megabytes:

```
233	sdcc-3.9.0
205	sdcc-3.9.0.buildtree
35	sdcc-3.9.0.installtree
```

Removing all `*.buildtree` in a `cpc-dev-tool-chain` installation saves a lot of space.
If is even possible to remove the matching sdcc (and others) source trees.
I may consider making `cpc-dev-tool-chain` fully out-of-source build later. Then each class of file would be in an overall directory, nothing to search inside to know what to remove.

## Lightweight cpc-dev-tool-chain

Also, from the beginning, `cpc-dev-tool-chain` was designed to be lightweight. A full git clone of it takes 4 megabytes, of which 2.5 megabytes are actual files, 1.6 megabytes is for the complete git history.

Compare with cpctelera (333 megabytes total, 67 megabytes git history, 226 megabytes actual files). cpc-dev-tool-chain is much lighter because the external tools are fetched and patched rather than included in the project history. Of course cpctelera includes so many things that cpc-dev-tool-chain does not even address, but most of the size difference is due to the architecture choice. Including sdcc alone is enough to multiply the side by 50.
